### ISSUE TITLE
Trying to login to AWS Toolkit in VS22 crashes the IDE

### ISSUE THREAD

**Issue by JoaoaoJ99** [aws/aws-toolkit-visual-studio#472]
Cannot login with my Builder ID account in AWS Toolkit in Visual Studio 2022, when i press the "Sign up or Sign in" button in the "Getting Started" tab.

1. Go to Extensions tab
2. In AWS Toolkit tab choose Getting Started option
3. Selected Amazon Q in step 1
4. Click Sign up or Sign in in step 2

I expected to login.

[log_2024-10-17_10-37-52_9320.txt](https://github.com/user-attachments/files/17409779/log_2024-10-17_10-37-52_9320.txt)

- Windows Version: Windows 11
- Visual Studio Version: VS22 17.11
- AWS Toolkit for Visual Studio Version: 17

**Comment by awschristou** [comment]
Thanks for reporting this issue. 

It sounds like you are trying to sign in using a Builder ID account. While we look into this, can you please try this workaround as there is an alternate way to connect with Builder ID:
- open a code file in the IDE
- use the Q margin menu at the bottom-left of the code file, and select Sign In
- select the `awsBuilderId` profile, and try to sign in

I'll be interested in hearing if you are able to get connected with this approach.

**Comment by JoaoaoJ99** [comment]
> Thanks for reporting this issue.
> 
> It sounds like you are trying to sign in using a Builder ID account. While we look into this, can you please try this workaround as there is an alternate way to connect with Builder ID:
> 
> * open a code file in the IDE
> * use the Q margin menu at the bottom-left of the code file, and select Sign In
> * select the `awsBuilderId` profile, and try to sign in
> 
> I'll be interested in hearing if you are able to get connected with this approach.

I went and tried this method i was able to find the menu, i click Sign In, choose the Builder ID which is the only option in the dropdown, i click Sign In and VS22 instantly stops responding. I'm not sure if maybe another extension is causing this issue but i just cannot login.

**Comment by awschristou** [comment]
Hi @JoaoaoJ99 , since you've opened this issue, we've released an updated Getting Started experience. Can you please download and install the latest version of the Toolkit, and try to sign in again?

**Comment by JoaoaoJ99** [comment]
Hey sorry for the late response, i have upgrade to the newest version still the same behaviour cant login in any way becuase it causes the IDE to crash

**Comment by awschristou** [comment]
Can you please share an updated Toolkit log from the newest version of the Toolkit that you installed?
