### ISSUE TITLE
Amazon Q Chat Window appears on top of all other windows

### ISSUE THREAD

**Issue by deanis74** [aws/aws-toolkit-visual-studio#523]
I have the Amazon Q Chat Window included in my stack of normal code windows, as a separate tab. It blocks out all other tool windows, which is not standard behavior.

** Steps to reproduce **
1. Open an Amazon Q Chat window
2. Dock it as one of your code tabs
3. Dock the Properties tool window to the left side, but don't pin it
4. Hover over the Properties tool window

**Expected behavior**
The Properties tool window appears over the Amazon Q Chat tab. You can see this behavior if you have another document tab active.

**Actual Behavior**
The Properties tool window appears behind and completely blocked by the Amazon Q Chat tab. None of the elements in the Amazon Q window are clickable because it isn't actually the foreground window, confirmed by the pointer not changing to the finger and remaining as the arrow.

Repeat this with Output/Error List/etc, which I usually dock as fly-outs to the bottom of the bottom of my VS workspace.

Amazon Q Chat obscuring the Properties tool window.
<img width="304" height="302" alt="Image" src="https://github.com/user-attachments/assets/ce16cdd8-122c-4e92-aec0-ad480dd3dd9b" />

Standard document window behaving nicely with the Properties tool window. Amazon Q Chat is still open and in the same tab position, it is just not active.
<img width="304" height="302" alt="Image" src="https://github.com/user-attachments/assets/ce16cdd8-122c-4e92-aec0-ad480dd3dd9b" />

**Development System (please complete the following information):**
- Windows Version: 11 23H2 22631.5624
- Visual Studio Version: 17.13.7
- AWS Toolkit for Visual Studio Version: 1.75.0.0

**Comment by leigh-pointer** [comment]
I would like to mention this is still an issue in visual studio 2026.

**Comment by deanis74** [comment]
Ping! Still wondering what that comment back in July meant.

Does the plug-in need to migrate to the drop-in replacement [WebViewCompositionControl](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/archive?tabs=dotnetcsharp#show-wpf-elements-on-top-of-the-webview2-layer-webview2compositioncontrol)?

**Comment by leigh-pointer** [comment]
@deanis74 It was fixed in the following update. Issue can be closed.

**Comment by deanis74** [comment]
@leigh-pointer if you are referring to 1.89.0.0 then no, it's still an issue.

<img width="496" height="347" alt="Image" src="https://github.com/user-attachments/assets/f1e56edf-5e47-4c49-b506-badafbd8a2d5" />

<img width="392" height="116" alt="Image" src="https://github.com/user-attachments/assets/1cb93bec-6814-49d6-b8ad-c0f7df837f9a" />

If you're referring to the release coming up after this one, I'm looking forward to it.
